### ISSUE TITLE
Project 2: Real-time Orca Call Detection in No Time

### ISSUE THREAD

**Issue by valentina-s** [orcasound/orcagsoc#3]
## Real-time Orca Call Detection in No Time

This project will focus on binary classification of orca calls in real time. 

Tonal whale sound detectors exist in open-source software (e.g. PAMGuard) and can run in real-time. However, these programs are not fully platform-independent, and little is known about how they perform in real-time compared to cloud-based real-time ML pipelines. 

The real-time orca prediction toolkit will provide an easy way to deploy trained models, and test them on a real-time audio streams. Users will be able to upload their models in standardized formats, and then deploy them on different data streams. The objective is to make the toolkit flexible enough to be adopted widely by passive acoustic researchers with little technical experience. The processing will occur on a public cloud provider, so the design is not limited by lab-specific servers. Optimizing the processing and minimizing the cost will be of prime importance. The project can be expanded to detect other sounds (by uploading other detectors), and allow comprehensive study of the ocean soundscape.

**Required skills:**  Python, deep learning, signal processing

**Bonus skills:** cloud computing, parallel processing, Docker

**Possible mentors:**  Jesse Lopez, Scott, Val, Valentina

**References and open-source building blocks:**

* Models: Tensorflow, Pytorch, Keras, Scikit-learn, [ONNX](https://onnx.ai/) format, [TensorflowJS](https://www.tensorflow.org/js)
* Parallel processing: Dask, Kubernetes, Flink, Cloud functions (e.g. lambda), [Github Actions](https://github.com/features/actions)
* Virtualization: docker
* [Ketos](https://docs.meridian.cs.dal.ca/ketos/): Python package for acoustic data analysis with neural networks
* Data streams:
	* Orcasound raw data: 
 `aws --no-sign-request s3 ls streaming-orcasound-net/rpi_bush_point/hls/`
(files are in .ts format (~10 sec each) , you can use ffmpeg to convert it to .avi)
	* Ocean Observatories Initiative data: 
[https://rawdata.oceanobservatories.org/files/RS01SLBS/LJ01A/09-HYDBBA102/2020/03/](https://rawdata.oceanobservatories.org/files/RS01SLBS/LJ01A/09-HYDBBA102/2020/03/)
(files are in the .mseed format which can be opened with the python [obspy](https://github.com/obspy/obspy) library)
* Existing classifiers:
	* OrcaCNN: [https://github.com/axiom-data-science/OrcaCNN/tree/master/Detection/Labelling](https://github.com/axiom-data-science/OrcaCNN/tree/master/Detection/Labelling) (Alaska Orcas - prelim)
	* Spectral Peaks: [https://github.com/orcasound/orcadata/tree/master/WAV_FLACprocessor_Val/ProcessLocalFilesForCalls](https://github.com/orcasound/orcadata/tree/master/WAV_FLACprocessor_Val/ProcessLocalFilesForCalls)

**Points to consider in the proposal:**

Design of the system:

* What are the inputs, what are the outputs?
* What are the package requirements?

Performance:

* How long does it take? What are the time limitations?
* What resources can be used to speed it up?
Is there associated cost?

**Getting started** (these are suggestions, there is no one way to go):

* Set up a [docker](https://docs.docker.com/get-started/) file for running a simple classifier: background noise vs something else (or one of the existing classifiers) on the Orcasound raw data.
* Use [github actions](https://help.github.com/en/actions) to set up an automatic classification on an Orcasound raw file.
* We will possibly have some cloud credits (form [Microsoft Azure](https://azure.microsoft.com/en-us/overview/#intro-to-cloud-computing)) for the summer! Explore what tools can be useful for your project (you do not have to set up an account, just read on the options and identify how they can be integrated with your work).

**Comment by rishiraj-acharya** [comment]
Really interesting project to work on. I am sharing my Draft Proposal to promote more open development of innovative ideas. Feedback from Mentors and Orcasound experts would be highly appreciated.

https://docs.google.com/document/d/1w7FtKRzoXLnWc350gh4cWn2Q_draUSNzT5DEnQacm-o/edit?usp=drivesdk

**Comment by MoAmrYehia** [comment]
This is my draft. Thank you for your time and I really excited for your feedback.  

https://docs.google.com/document/d/1p3Xf86C6ciit4K3tIVujX4fbfSHa4Cb0JUB-J7xVY_4/edit?usp=sharing

**Comment by nikhilrana015** [comment]
Hello mentors, here is the link of GSoC draft. Excited for your feedback.
https://docs.google.com/document/d/1o7WRiHJW01YWgxkNnH56J9cKfpiJQJWNoNP8JDb8C48/edit?usp=sharing

**Comment by nikhilrana015** [comment]
This is my GSoC draft. Excited for your feedback.
https://docs.google.com/document/d/1o7WRiHJW01YWgxkNnH56J9cKfpiJQJWNoNP8JDb8C48/edit?usp=sharing

**Comment by sainimohit23** [comment]
@rishiraj-acharya @nikhilrana015 I am so furious that you guys have completely ripped off the work that I did last year for the ESIP. I was not very experienced back then(though I'm still not), still, I gave my everything to this project. It took me more than two months of sleepless nights to come up with a working pipeline. I spent a lot of time curating the training data from absolute scratch which included manually trimming down the audio clips, fixing the frequency of audio, standardizing the channels and many other fixes. It took me days of coding and lots of mathematical calculations to come up with the design and implementation of the sliding window mechanism for long audio inputs. The same mechanism can be used in this project to give results in real-time.

Every step(except the last one because it is a new requirement of this project) and the Idea mentioned in the proposal of @rishiraj-acharya is directly taken from my repository and there isn't a single mention my work. You can find the working code with data in this part of my repo: https://github.com/sainimohit23/OrcaCNN-Demo/tree/master/2%20RNN%20Orca%20Detection%20model . There is no way someone can come up with the exact same idea with all the small details figured out in just 4 days.

I can even show the raw code that I used for the development of this project which is not on GitHub. I can also share my last year's proposal and it has a way more detailed explanation of the technical aspects of the pipeline with diagrams.

After the last year's results were announced I thought that it's over. So I shared the code on Github so that it can be used by other researchers for further development in the field. During last year's GSoC I also worked on a project called `Sanskrit sandhi splitter` for the organization CLTK. The organization was not selected. So, with a similar motivation, I published the code on my GitHub. And you can check, it now has stars from two Sanskrit research scholars. Here is the code- https://github.com/sainimohit23/cltk/tree/master/cltk/stem/sanskrit/code

It's my request to the admins, please look into this. It really hurts when someone gets all the praise and tries to capitalize on the work you did with your full dedication.

**Comment by dharmsen** [comment]
Linked here is my preliminary draft. I look forward to hearing your feedback. Thanks in advance for your time.
https://docs.google.com/document/d/1rNihm7jI5eBdJRP2d1YxVSK3JpxUByLXBaPtVSkU4AE/edit?usp=sharing

**Comment by abhinav99ash29** [comment]
Here is my draft for idea 2. Please share your feedback
Thanks

https://docs.google.com/document/d/1B_RC4_j57e1ceTXjvaa1w3llBWk48LWbxLubOY945LE/edit?usp=sharing

**Comment by sainimohit23** [comment]
Here is my draft for the given project:

https://docs.google.com/document/d/1FnwVOES2W4ibBjGuVFIwSM59_tXxJFQZlkajF5s_z-M/edit?usp=sharing

**Comment by yusufkhanmohammad** [comment]
Hello Community Members!
Here is the link to my draft for Idea 2,
Looking forward for your valuable feedback.

https://docs.google.com/document/d/1NY8oZbMx7j1IOUiJH1V8KYUXLpGDYZz4RjjtGq5dUbU/edit?usp=sharing

**Comment by scottveirs** [comment]
A participant in a hackathon at Microsoft related to Orcasound mentioned this Python toolbox. Anyone have any experience with it (@valentina-s ?), or a sense of whether it could be a useful tool for this project?

https://tut-arg.github.io/sed_eval/index.html

**Comment by sainimohit23** [comment]
Hi @scottveirs , I read the documentation of **SED EVAL** toolkit. This toolkit provides the metrics to evaluate the performance of models on the task of sound event detection. And yes it can be used to evaluate the performance of the models for this project.

**Comment by atreyamaj** [comment]
Hello Mentors! Here is the link to my draft for Project 2. 
https://docs.google.com/document/d/1OKgHNGlshNkoRhs6argPi2rYPseX7vc_owarpCK2WQI/edit?usp=sharing
It would be great if you could provide me with some feedback in these final few hours until submission. Thank you for your time.
Atreya Majumdar.
